plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

initFields:
  main: dist/index.js
  tscmono:
    preset: default
initScope: tech-debt

packageExtensions:
  "@prisma/engine-core@3.3.0":
    dependencies:
      "strip-ansi": "6.0.1"
  "graphql.macro@*":
    dependencies:
      "@babel/runtime": "*"
  "graphql-tag@*":
    dependencies:
      "graphql": "*"
